const contracts = [
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' },
  { title: 'My Contract' }
];

export default contracts;
